package com.merryapps.tictacpro.model.db;

import com.merryapps.framework.EntityState;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DIFFICULTY".
 */
public class DifficultyEntity implements com.merryapps.framework.Entity {

    private Long id;
    private int type;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String description;
    private int secondsAddedOnCorrectMove;
    private int secondsSubtractedOnCorrectMove;
    private int minimumScoreToUnlockNextDifficulty;
    private boolean isLocked;
    /** Not-null value. */
    private EntityState entityState;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DifficultyEntity() {
    }

    public DifficultyEntity(Long id) {
        this.id = id;
    }

    public DifficultyEntity(Long id, int type, String name, String description, int secondsAddedOnCorrectMove, int secondsSubtractedOnCorrectMove, int minimumScoreToUnlockNextDifficulty, boolean isLocked, EntityState entityState) {
        this.id = id;
        this.type = type;
        this.name = name;
        this.description = description;
        this.secondsAddedOnCorrectMove = secondsAddedOnCorrectMove;
        this.secondsSubtractedOnCorrectMove = secondsSubtractedOnCorrectMove;
        this.minimumScoreToUnlockNextDifficulty = minimumScoreToUnlockNextDifficulty;
        this.isLocked = isLocked;
        this.entityState = entityState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(String description) {
        this.description = description;
    }

    public int getSecondsAddedOnCorrectMove() {
        return secondsAddedOnCorrectMove;
    }

    public void setSecondsAddedOnCorrectMove(int secondsAddedOnCorrectMove) {
        this.secondsAddedOnCorrectMove = secondsAddedOnCorrectMove;
    }

    public int getSecondsSubtractedOnCorrectMove() {
        return secondsSubtractedOnCorrectMove;
    }

    public void setSecondsSubtractedOnCorrectMove(int secondsSubtractedOnCorrectMove) {
        this.secondsSubtractedOnCorrectMove = secondsSubtractedOnCorrectMove;
    }

    public int getMinimumScoreToUnlockNextDifficulty() {
        return minimumScoreToUnlockNextDifficulty;
    }

    public void setMinimumScoreToUnlockNextDifficulty(int minimumScoreToUnlockNextDifficulty) {
        this.minimumScoreToUnlockNextDifficulty = minimumScoreToUnlockNextDifficulty;
    }

    public boolean getIsLocked() {
        return isLocked;
    }

    public void setIsLocked(boolean isLocked) {
        this.isLocked = isLocked;
    }

    /** Not-null value. */
    public EntityState getEntityState() {
        return entityState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEntityState(EntityState entityState) {
        this.entityState = entityState;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        DifficultyEntity that = (DifficultyEntity) o;

        return id != null ? id.equals(that.id) : that.id == null;

    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    @Override
    public String toString() {
        return "DifficultyEntity{" +
                "id=" + id +
                ", type=" + type +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", secondsAddedOnCorrectMove=" + secondsAddedOnCorrectMove +
                ", secondsSubtractedOnCorrectMove=" + secondsSubtractedOnCorrectMove +
                ", minimumScoreToUnlockNextDifficulty=" + minimumScoreToUnlockNextDifficulty +
                ", isLocked=" + isLocked +
                ", entityState=" + entityState +
                '}';
    }
    // KEEP METHODS END

}
