package com.merryapps.tictacpro.model.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.merryapps.framework.EntityStateConverter;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_STATS".
*/
public class GlobalStatsEntityDao extends AbstractDao<GlobalStatsEntity, Long> {

    public static final String TABLENAME = "USER_STATS";

    /**
     * Properties of entity GlobalStatsEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DifficultyId = new Property(1, Long.class, "difficultyId", false, "DIFFICULTY_ID");
        public final static Property SoundPref = new Property(2, String.class, "soundPref", false, "SOUND_PREF");
        public final static Property GameState = new Property(3, String.class, "gameState", false, "GAME_STATE");
        public final static Property EntityState = new Property(4, String.class, "entityState", false, "ENTITY_STATE");
    };

    private DaoSession daoSession;

    private final SoundPrefConverter soundPrefConverter = new SoundPrefConverter();
    private final GameStateConverter gameStateConverter = new GameStateConverter();
    private final EntityStateConverter entityStateConverter = new EntityStateConverter();

    public GlobalStatsEntityDao(DaoConfig config) {
        super(config);
    }
    
    public GlobalStatsEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_STATS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DIFFICULTY_ID\" INTEGER," + // 1: difficultyId
                "\"SOUND_PREF\" TEXT NOT NULL ," + // 2: soundPref
                "\"GAME_STATE\" TEXT NOT NULL ," + // 3: gameState
                "\"ENTITY_STATE\" TEXT NOT NULL );"); // 4: entityState
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_STATS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GlobalStatsEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long difficultyId = entity.getDifficultyId();
        if (difficultyId != null) {
            stmt.bindLong(2, difficultyId);
        }
        stmt.bindString(3, soundPrefConverter.convertToDatabaseValue(entity.getSoundPref()));
        stmt.bindString(4, gameStateConverter.convertToDatabaseValue(entity.getGameState()));
        stmt.bindString(5, entityStateConverter.convertToDatabaseValue(entity.getEntityState()));
    }

    @Override
    protected void attachEntity(GlobalStatsEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GlobalStatsEntity readEntity(Cursor cursor, int offset) {
        GlobalStatsEntity entity = new GlobalStatsEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // difficultyId
            soundPrefConverter.convertToEntityProperty(cursor.getString(offset + 2)), // soundPref
            gameStateConverter.convertToEntityProperty(cursor.getString(offset + 3)), // gameState
            entityStateConverter.convertToEntityProperty(cursor.getString(offset + 4)) // entityState
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GlobalStatsEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDifficultyId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSoundPref(soundPrefConverter.convertToEntityProperty(cursor.getString(offset + 2)));
        entity.setGameState(gameStateConverter.convertToEntityProperty(cursor.getString(offset + 3)));
        entity.setEntityState(entityStateConverter.convertToEntityProperty(cursor.getString(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GlobalStatsEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GlobalStatsEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDifficultyEntityDao().getAllColumns());
            builder.append(" FROM USER_STATS T");
            builder.append(" LEFT JOIN DIFFICULTY T0 ON T.\"DIFFICULTY_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GlobalStatsEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        GlobalStatsEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DifficultyEntity difficultyEntity = loadCurrentOther(daoSession.getDifficultyEntityDao(), cursor, offset);
        entity.setDifficultyEntity(difficultyEntity);

        return entity;    
    }

    public GlobalStatsEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GlobalStatsEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GlobalStatsEntity> list = new ArrayList<GlobalStatsEntity>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GlobalStatsEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GlobalStatsEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
