package com.merryapps.tictacpro.model.db;

import com.merryapps.framework.EntityState;
import com.merryapps.tictacpro.model.game.Token;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LEVEL".
 */
public class LevelEntity implements com.merryapps.framework.Entity {

    private Long id;
    private int levelNumber;
    /** Not-null value. */
    private String board;
    /** Not-null value. */
    private Token firstMoveToken;
    /** Not-null value. */
    private EntityState entityState;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LevelEntity() {
    }

    public LevelEntity(Long id) {
        this.id = id;
    }

    public LevelEntity(Long id, int levelNumber, String board, Token firstMoveToken, EntityState entityState) {
        this.id = id;
        this.levelNumber = levelNumber;
        this.board = board;
        this.firstMoveToken = firstMoveToken;
        this.entityState = entityState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getLevelNumber() {
        return levelNumber;
    }

    public void setLevelNumber(int levelNumber) {
        this.levelNumber = levelNumber;
    }

    /** Not-null value. */
    public String getBoard() {
        return board;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBoard(String board) {
        this.board = board;
    }

    /** Not-null value. */
    public Token getFirstMoveToken() {
        return firstMoveToken;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstMoveToken(Token firstMoveToken) {
        this.firstMoveToken = firstMoveToken;
    }

    /** Not-null value. */
    public EntityState getEntityState() {
        return entityState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEntityState(EntityState entityState) {
        this.entityState = entityState;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
