package com.merryapps.tictacpro.model.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.merryapps.framework.EntityStateConverter;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LEVEL".
*/
public class LevelEntityDao extends AbstractDao<LevelEntity, Long> {

    public static final String TABLENAME = "LEVEL";

    /**
     * Properties of entity LevelEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LevelNumber = new Property(1, int.class, "levelNumber", false, "LEVEL_NUMBER");
        public final static Property Board = new Property(2, String.class, "board", false, "BOARD");
        public final static Property FirstMoveToken = new Property(3, String.class, "firstMoveToken", false, "FIRST_MOVE_TOKEN");
        public final static Property EntityState = new Property(4, String.class, "entityState", false, "ENTITY_STATE");
    };

    private final TokenConverter firstMoveTokenConverter = new TokenConverter();
    private final EntityStateConverter entityStateConverter = new EntityStateConverter();

    public LevelEntityDao(DaoConfig config) {
        super(config);
    }
    
    public LevelEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LEVEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LEVEL_NUMBER\" INTEGER NOT NULL UNIQUE ," + // 1: levelNumber
                "\"BOARD\" TEXT NOT NULL UNIQUE ," + // 2: board
                "\"FIRST_MOVE_TOKEN\" TEXT NOT NULL ," + // 3: firstMoveToken
                "\"ENTITY_STATE\" TEXT NOT NULL );"); // 4: entityState
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LEVEL\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LevelEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLevelNumber());
        stmt.bindString(3, entity.getBoard());
        stmt.bindString(4, firstMoveTokenConverter.convertToDatabaseValue(entity.getFirstMoveToken()));
        stmt.bindString(5, entityStateConverter.convertToDatabaseValue(entity.getEntityState()));
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LevelEntity readEntity(Cursor cursor, int offset) {
        LevelEntity entity = new LevelEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // levelNumber
            cursor.getString(offset + 2), // board
            firstMoveTokenConverter.convertToEntityProperty(cursor.getString(offset + 3)), // firstMoveToken
            entityStateConverter.convertToEntityProperty(cursor.getString(offset + 4)) // entityState
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LevelEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLevelNumber(cursor.getInt(offset + 1));
        entity.setBoard(cursor.getString(offset + 2));
        entity.setFirstMoveToken(firstMoveTokenConverter.convertToEntityProperty(cursor.getString(offset + 3)));
        entity.setEntityState(entityStateConverter.convertToEntityProperty(cursor.getString(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LevelEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LevelEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
